// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdC-326QCw6mfv8xbkqw08D94y3aQjnss',
    appId: '1:464509388731:web:0734941d5b46d90f65669e',
    messagingSenderId: '464509388731',
    projectId: 'arogyasetuner',
    authDomain: 'arogyasetuner.firebaseapp.com',
    databaseURL: 'https://arogyasetuner-default-rtdb.firebaseio.com',
    storageBucket: 'arogyasetuner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_-8xz9NLF-igTosNnbkHDgR8o5-cFEo',
    appId: '1:464509388731:android:9163beed8d2e0be965669e',
    messagingSenderId: '464509388731',
    projectId: 'arogyasetuner',
    databaseURL: 'https://arogyasetuner-default-rtdb.firebaseio.com',
    storageBucket: 'arogyasetuner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNNR6UkaA0hFRfOaciX5IWxUCFXD8SeI',
    appId: '1:464509388731:ios:2398fed8b34fb17b65669e',
    messagingSenderId: '464509388731',
    projectId: 'arogyasetuner',
    databaseURL: 'https://arogyasetuner-default-rtdb.firebaseio.com',
    storageBucket: 'arogyasetuner.firebasestorage.app',
    iosBundleId: 'com.example.arogyasetuner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZNNR6UkaA0hFRfOaciX5IWxUCFXD8SeI',
    appId: '1:464509388731:ios:2398fed8b34fb17b65669e',
    messagingSenderId: '464509388731',
    projectId: 'arogyasetuner',
    databaseURL: 'https://arogyasetuner-default-rtdb.firebaseio.com',
    storageBucket: 'arogyasetuner.firebasestorage.app',
    iosBundleId: 'com.example.arogyasetuner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdC-326QCw6mfv8xbkqw08D94y3aQjnss',
    appId: '1:464509388731:web:ccdac5fdbb3201f965669e',
    messagingSenderId: '464509388731',
    projectId: 'arogyasetuner',
    authDomain: 'arogyasetuner.firebaseapp.com',
    databaseURL: 'https://arogyasetuner-default-rtdb.firebaseio.com',
    storageBucket: 'arogyasetuner.firebasestorage.app',
  );
}
